// NEXUS National Resource Registry — Firestore Seed Data
// Collection: resources/{resourceId}
// Run with: node firestore_seed.js

const admin = require("firebase-admin");

// ============================================================
// CONFIGURATION — Update this path to your service account key
// Download from: Firebase Console > Project Settings > Service Accounts > Generate New Private Key
// ============================================================
const serviceAccount = require("../serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();
const now = admin.firestore.Timestamp.now();

// ============================================================
// SEED DATA
// ============================================================

const resources = [

  // ==================== ACTIVE HEALTH LABS ====================

  {
    resourceId: "AHL-001",
    name: "Active Health Lab @ Bishan Swimming Complex",
    type: "active_health_lab",
    region: "central",
    planningAreas: ["Bishan", "Toa Payoh", "Ang Mo Kio"],
    postalCode: "579778",
    postalSectorPrefix: "57",
    address: "1 Bishan Street 14, Singapore 579778",
    operator: "Sport Singapore",
    contactPhone: "",
    contactEmail: "",
    bookingPlatform: "MyActiveSG+",
    bookingUrl: "https://members.myactivesg.com/programmes",
    programmes: [
      { name: "Balance & Muscular Fitness Workshop", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Body Composition Assessment", intensity: "low", sessions: 1, priceSgd: 7 },
      { name: "Manage Metabolic Health", intensity: "moderate", sessions: 7, priceSgd: 48 },
      { name: "Strength 1.0", intensity: "moderate", sessions: 8, priceSgd: 60 },
      { name: "Strength 2.0 — Foundation", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Strength 2.0 — Assessment & Check-in", intensity: "moderate", sessions: 1, priceSgd: 7 },
      { name: "Perform 2.0 — AMRAP", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — ENGINE", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — Multi-Modal", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "CALM 1.0 (seniors 60+)", intensity: "moderate", sessions: 8, priceSgd: 48 },
      { name: "CALM 2.0 (seniors 60+)", intensity: "moderate", sessions: 6, priceSgd: 36 },
    ],
    intensityRange: ["low", "moderate", "vigorous"],
    priceRangeSgd: { min: 6, max: 60 },
    eligibility: ["all_adults"],
    healthierSgLinked: true,
    sdohAlignment: [],
    tags: ["exercise", "fitness", "assessment", "strength", "metabolic", "seniors", "group", "coached"],
    operatingHours: "Tue-Fri: 10.30am-8pm, Sat: 9am-5pm, Sun: 9am-2pm. Closed Mon & PH. Closed 1-4pm Tue-Fri, 1-2pm Sat.",
    latitude: 1.3521,
    longitude: 103.8480,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.activesgcircle.gov.sg/activehealth/find-us",
    notes: "Side entrance on right side of swimming pool. Pre-booking required.",
  },

  {
    resourceId: "AHL-002",
    name: "Active Health Lab @ Decathlon Singapore Lab",
    type: "active_health_lab",
    region: "central",
    planningAreas: ["Kallang", "Geylang", "Mountbatten"],
    postalCode: "397799",
    postalSectorPrefix: "39",
    address: "230 Stadium Boulevard (Kallang Wave Mall), Singapore 397799",
    operator: "Sport Singapore x Decathlon",
    contactPhone: "",
    contactEmail: "",
    bookingPlatform: "MyActiveSG+",
    bookingUrl: "https://members.myactivesg.com/programmes",
    programmes: [
      { name: "Body Composition Assessment", intensity: "low", sessions: 1, priceSgd: 7 },
      { name: "Balance & Muscular Fitness Workshop", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Strength 2.0 — Foundation", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — AMRAP", intensity: "vigorous", sessions: 1, priceSgd: 6 },
    ],
    intensityRange: ["low", "moderate", "vigorous"],
    priceRangeSgd: { min: 6, max: 48 },
    eligibility: ["all_adults"],
    healthierSgLinked: true,
    sdohAlignment: [],
    tags: ["exercise", "fitness", "assessment", "strength", "group", "coached"],
    operatingHours: "Refer to ActiveSG website for current hours.",
    latitude: 1.3025,
    longitude: 103.8754,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.activesgcircle.gov.sg/activehealth/find-us",
    notes: "Beside Decathlon entrance at Kallang Wave Mall.",
  },

  {
    resourceId: "AHL-003",
    name: "Active Health Lab @ Delta Sport Centre",
    type: "active_health_lab",
    region: "central",
    planningAreas: ["Tiong Bahru", "Bukit Merah", "Queenstown", "Redhill"],
    postalCode: "158790",
    postalSectorPrefix: "15",
    address: "900 Tiong Bahru Road, Level 2, Singapore 158790",
    operator: "Sport Singapore",
    contactPhone: "",
    contactEmail: "",
    bookingPlatform: "MyActiveSG+",
    bookingUrl: "https://members.myactivesg.com/programmes",
    programmes: [
      { name: "Balance & Muscular Fitness Workshop", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Body Composition Assessment", intensity: "low", sessions: 1, priceSgd: 7 },
      { name: "Manage Metabolic Health", intensity: "moderate", sessions: 7, priceSgd: 48 },
      { name: "Strength 1.0", intensity: "moderate", sessions: 8, priceSgd: 60 },
      { name: "Strength 2.0 — Foundation", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "CALM 1.0 (seniors 60+)", intensity: "moderate", sessions: 8, priceSgd: 48 },
      { name: "CALM 2.0 (seniors 60+)", intensity: "moderate", sessions: 6, priceSgd: 36 },
    ],
    intensityRange: ["low", "moderate", "vigorous"],
    priceRangeSgd: { min: 6, max: 60 },
    eligibility: ["all_adults"],
    healthierSgLinked: true,
    sdohAlignment: [],
    tags: ["exercise", "fitness", "assessment", "strength", "metabolic", "seniors", "group", "coached"],
    operatingHours: "Tue-Fri: 10.30am-8pm, Sat: 9am-5pm. Closed Mon, Sun & PH.",
    latitude: 1.2891,
    longitude: 103.8227,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.activesgcircle.gov.sg/activehealth/find-us",
    notes: "Walking distance from Tiong Bahru MRT. Pre-booking required.",
  },

  {
    resourceId: "AHL-004",
    name: "Active Health Lab @ Heartbeat@Bedok",
    type: "active_health_lab",
    region: "east",
    planningAreas: ["Bedok", "Kampong Chai Chee", "Eunos", "Kembangan"],
    postalCode: "469662",
    postalSectorPrefix: "46",
    address: "11 Bedok North Street 1, #04-01, Heartbeat@Bedok, Singapore 469662",
    operator: "Sport Singapore",
    contactPhone: "",
    contactEmail: "",
    bookingPlatform: "MyActiveSG+",
    bookingUrl: "https://members.myactivesg.com/programmes",
    programmes: [
      { name: "Balance & Muscular Fitness Workshop", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Body Composition Assessment", intensity: "low", sessions: 1, priceSgd: 7 },
      { name: "Manage Metabolic Health", intensity: "moderate", sessions: 7, priceSgd: 48 },
      { name: "Strength 1.0", intensity: "moderate", sessions: 8, priceSgd: 60 },
      { name: "Strength 2.0 — Foundation", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — AMRAP", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — ENGINE", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "CALM 1.0 (seniors 60+)", intensity: "moderate", sessions: 8, priceSgd: 48 },
      { name: "CALM 2.0 (seniors 60+)", intensity: "moderate", sessions: 6, priceSgd: 36 },
    ],
    intensityRange: ["low", "moderate", "vigorous"],
    priceRangeSgd: { min: 6, max: 60 },
    eligibility: ["all_adults"],
    healthierSgLinked: true,
    sdohAlignment: [],
    tags: ["exercise", "fitness", "assessment", "strength", "metabolic", "seniors", "aqua", "group", "coached"],
    operatingHours: "Tue-Fri: 10.30am-8pm, Sat: 9am-5pm, Sun: 9am-2pm. Closed Mon & PH. Closed 1-2pm Tue-Sat.",
    latitude: 1.3265,
    longitude: 103.9318,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.activesgcircle.gov.sg/activehealth/find-us",
    notes: "Integrated hub — co-located with AAC (Care), polyclinic, CC, library. Outdoor pool for aqua programmes.",
  },

  {
    resourceId: "AHL-005",
    name: "Active Health Lab @ Our Tampines Hub",
    type: "active_health_lab",
    region: "east",
    planningAreas: ["Tampines", "Pasir Ris", "Simei"],
    postalCode: "528523",
    postalSectorPrefix: "52",
    address: "1 Tampines Walk, #03-32, Singapore 528523",
    operator: "Sport Singapore",
    contactPhone: "",
    contactEmail: "",
    bookingPlatform: "MyActiveSG+",
    bookingUrl: "https://members.myactivesg.com/programmes",
    programmes: [
      { name: "Balance & Muscular Fitness Workshop", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Body Composition Assessment", intensity: "low", sessions: 1, priceSgd: 7 },
      { name: "Manage Metabolic Health", intensity: "moderate", sessions: 7, priceSgd: 48 },
      { name: "Strength 1.0", intensity: "moderate", sessions: 8, priceSgd: 60 },
      { name: "Strength 2.0 — Foundation", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — AMRAP", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — ENGINE", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — Multi-Modal", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "Knee MSK Management", intensity: "moderate", sessions: 7, priceSgd: 48 },
      { name: "CALM 1.0 (seniors 60+)", intensity: "moderate", sessions: 8, priceSgd: 48 },
      { name: "CALM 2.0 (seniors 60+)", intensity: "moderate", sessions: 6, priceSgd: 36 },
    ],
    intensityRange: ["low", "moderate", "vigorous"],
    priceRangeSgd: { min: 6, max: 60 },
    eligibility: ["all_adults"],
    healthierSgLinked: true,
    sdohAlignment: [],
    tags: ["exercise", "fitness", "assessment", "strength", "metabolic", "knee", "seniors", "group", "coached"],
    operatingHours: "Tue-Fri: 10.30am-8pm, Sat: 9am-5pm. Closed Mon, Sun & PH.",
    latitude: 1.3527,
    longitude: 103.9405,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.activesgcircle.gov.sg/activehealth/find-us",
    notes: "Full suite including Knee MSK. Pre-booking via MyActiveSG+ required.",
  },

  {
    resourceId: "AHL-006",
    name: "Active Health Lab @ Sengkang Sport Centre",
    type: "active_health_lab",
    region: "north_east",
    planningAreas: ["Sengkang", "Hougang", "Buangkok"],
    postalCode: "544964",
    postalSectorPrefix: "54",
    address: "57 Anchorvale Road, #02-07, Singapore 544964",
    operator: "Sport Singapore",
    contactPhone: "",
    contactEmail: "",
    bookingPlatform: "MyActiveSG+",
    bookingUrl: "https://members.myactivesg.com/programmes",
    programmes: [
      { name: "Balance & Muscular Fitness Workshop", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Body Composition Assessment", intensity: "low", sessions: 1, priceSgd: 7 },
      { name: "Manage Metabolic Health", intensity: "moderate", sessions: 7, priceSgd: 48 },
      { name: "Strength 1.0", intensity: "moderate", sessions: 8, priceSgd: 60 },
      { name: "Strength 2.0 — Foundation", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — AMRAP", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "CALM 1.0 (seniors 60+)", intensity: "moderate", sessions: 8, priceSgd: 48 },
      { name: "CALM 2.0 (seniors 60+)", intensity: "moderate", sessions: 6, priceSgd: 36 },
    ],
    intensityRange: ["low", "moderate", "vigorous"],
    priceRangeSgd: { min: 6, max: 60 },
    eligibility: ["all_adults"],
    healthierSgLinked: true,
    sdohAlignment: [],
    tags: ["exercise", "fitness", "assessment", "strength", "metabolic", "seniors", "group", "coached"],
    operatingHours: "Tue-Fri: 10.30am-8pm, Sat: 9am-5pm. Closed Mon, Sun & PH.",
    latitude: 1.3914,
    longitude: 103.8915,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.activesgcircle.gov.sg/activehealth/find-us",
    notes: "Primary lab for North-East region. Pre-booking via MyActiveSG+ required.",
  },

  {
    resourceId: "AHL-007",
    name: "Active Health Lab @ Northshore Plaza (Punggol)",
    type: "active_health_lab",
    region: "north_east",
    planningAreas: ["Punggol", "Punggol Northshore"],
    postalCode: "820407",
    postalSectorPrefix: "82",
    address: "407 Northshore Drive, #01-27, Singapore 820407",
    operator: "Sport Singapore",
    contactPhone: "",
    contactEmail: "",
    bookingPlatform: "MyActiveSG+",
    bookingUrl: "https://members.myactivesg.com/programmes",
    programmes: [
      { name: "Balance & Muscular Fitness Workshop", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Body Composition Assessment", intensity: "low", sessions: 1, priceSgd: 7 },
      { name: "Strength 2.0 — Foundation", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — AMRAP", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "CALM 1.0 (seniors 60+)", intensity: "moderate", sessions: 8, priceSgd: 48 },
    ],
    intensityRange: ["low", "moderate", "vigorous"],
    priceRangeSgd: { min: 6, max: 48 },
    eligibility: ["all_adults"],
    healthierSgLinked: true,
    sdohAlignment: [],
    tags: ["exercise", "fitness", "assessment", "strength", "seniors", "group", "coached"],
    operatingHours: "Refer to ActiveSG website for current hours.",
    latitude: 1.4131,
    longitude: 103.9159,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.activesgcircle.gov.sg/activehealth/find-us",
    notes: "Waterfront precinct. Ideal for young families and working adults.",
  },

  {
    resourceId: "AHL-008",
    name: "Active Health Lab @ Jurong East Sport Centre",
    type: "active_health_lab",
    region: "west",
    planningAreas: ["Jurong East", "Jurong West", "Clementi", "Bukit Batok"],
    postalCode: "609517",
    postalSectorPrefix: "60",
    address: "21 Jurong East Street 31, #02-03, Singapore 609517",
    operator: "Sport Singapore",
    contactPhone: "",
    contactEmail: "",
    bookingPlatform: "MyActiveSG+",
    bookingUrl: "https://members.myactivesg.com/programmes",
    programmes: [
      { name: "Balance & Muscular Fitness Workshop", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Body Composition Assessment", intensity: "low", sessions: 1, priceSgd: 7 },
      { name: "Manage Metabolic Health", intensity: "moderate", sessions: 7, priceSgd: 48 },
      { name: "Strength 1.0", intensity: "moderate", sessions: 8, priceSgd: 60 },
      { name: "Strength 2.0 — Foundation", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — AMRAP", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — ENGINE", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "Knee MSK Management", intensity: "moderate", sessions: 7, priceSgd: 48 },
      { name: "CALM 1.0 (seniors 60+)", intensity: "moderate", sessions: 8, priceSgd: 48 },
      { name: "CALM 2.0 (seniors 60+)", intensity: "moderate", sessions: 6, priceSgd: 36 },
    ],
    intensityRange: ["low", "moderate", "vigorous"],
    priceRangeSgd: { min: 6, max: 60 },
    eligibility: ["all_adults"],
    healthierSgLinked: true,
    sdohAlignment: [],
    tags: ["exercise", "fitness", "assessment", "strength", "metabolic", "knee", "seniors", "group", "coached"],
    operatingHours: "Tue-Fri: 10.30am-8pm, Sat: 9am-5pm. Closed Mon, Sun & PH.",
    latitude: 1.3329,
    longitude: 103.7436,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.activesgcircle.gov.sg/activehealth/find-us",
    notes: "Only Active Health Lab serving the entire West region. Adjacent to Jurong East MRT interchange. Full suite including Knee MSK.",
  },

  {
    resourceId: "AHL-009",
    name: "Active Health Lab @ Woodlands Sport Centre",
    type: "active_health_lab",
    region: "north",
    planningAreas: ["Woodlands", "Admiralty", "Marsiling"],
    postalCode: "738600",
    postalSectorPrefix: "73",
    address: "3 Woodlands Street 13, Singapore 738600",
    operator: "Sport Singapore",
    contactPhone: "",
    contactEmail: "",
    bookingPlatform: "MyActiveSG+",
    bookingUrl: "https://members.myactivesg.com/programmes",
    programmes: [
      { name: "Balance & Muscular Fitness Workshop", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Body Composition Assessment", intensity: "low", sessions: 1, priceSgd: 7 },
      { name: "Manage Metabolic Health", intensity: "moderate", sessions: 7, priceSgd: 48 },
      { name: "Strength 1.0", intensity: "moderate", sessions: 8, priceSgd: 60 },
      { name: "Strength 2.0 — Foundation", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Strength 2.0 — Assessment & Check-in", intensity: "moderate", sessions: 1, priceSgd: 7 },
      { name: "Perform 2.0 — AMRAP", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — ENGINE", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — Multi-Modal", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — Assessment & Check-in", intensity: "vigorous", sessions: 1, priceSgd: 7 },
      { name: "CALM 1.0 (seniors 60+)", intensity: "moderate", sessions: 8, priceSgd: 48 },
      { name: "CALM 2.0 (seniors 60+)", intensity: "moderate", sessions: 6, priceSgd: 36 },
    ],
    intensityRange: ["low", "moderate", "vigorous"],
    priceRangeSgd: { min: 6, max: 60 },
    eligibility: ["all_adults"],
    healthierSgLinked: true,
    sdohAlignment: [],
    tags: ["exercise", "fitness", "assessment", "strength", "metabolic", "seniors", "group", "coached"],
    operatingHours: "Tue-Fri: 10.30am-8pm, Sat: 9am-5pm. Closed Mon, Sun & PH.",
    latitude: 1.4362,
    longitude: 103.7865,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.activesgcircle.gov.sg/activehealth/find-us",
    notes: "Flagship North lab. Full suite. Beside ActiveSG Gym.",
  },

  {
    resourceId: "AHL-010",
    name: "Active Health Lab @ Bukit Canberra",
    type: "active_health_lab",
    region: "north",
    planningAreas: ["Canberra", "Sembawang", "Yishun"],
    postalCode: "756973",
    postalSectorPrefix: "75",
    address: "21 Canberra Link, #02-61, Singapore 756973",
    operator: "Sport Singapore",
    contactPhone: "",
    contactEmail: "",
    bookingPlatform: "MyActiveSG+",
    bookingUrl: "https://members.myactivesg.com/programmes",
    programmes: [
      { name: "Balance & Muscular Fitness Workshop", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Body Composition Assessment", intensity: "low", sessions: 1, priceSgd: 7 },
      { name: "Strength 1.0", intensity: "moderate", sessions: 8, priceSgd: 60 },
      { name: "Strength 2.0 — Foundation", intensity: "moderate", sessions: 1, priceSgd: 6 },
      { name: "Perform 2.0 — AMRAP", intensity: "vigorous", sessions: 1, priceSgd: 6 },
      { name: "CALM 1.0 (seniors 60+)", intensity: "moderate", sessions: 8, priceSgd: 48 },
      { name: "CALM 2.0 (seniors 60+)", intensity: "moderate", sessions: 6, priceSgd: 36 },
    ],
    intensityRange: ["low", "moderate", "vigorous"],
    priceRangeSgd: { min: 6, max: 60 },
    eligibility: ["all_adults"],
    healthierSgLinked: true,
    sdohAlignment: [],
    tags: ["exercise", "fitness", "assessment", "strength", "seniors", "group", "coached"],
    operatingHours: "Tue-Fri: 10.30am-8pm, Sat: 9am-5pm. Closed Mon, Sun & PH.",
    latitude: 1.4432,
    longitude: 103.8286,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.activesgcircle.gov.sg/activehealth/find-us",
    notes: "Serves Canberra, Sembawang, Yishun corridor.",
  },

  // ==================== ACTIVE AGEING CENTRES ====================

  {
    resourceId: "AAC-C01",
    name: "NTUC Health Active Ageing Centre (Lengkok Bahru)",
    type: "aac",
    region: "central",
    planningAreas: ["Bukit Merah", "Redhill", "Tiong Bahru"],
    postalCode: "151057",
    postalSectorPrefix: "15",
    address: "57 Lengkok Bahru, #01-491, Singapore 151057",
    operator: "NTUC Health",
    contactPhone: "",
    contactEmail: "activeageing@ntuchealth.sg",
    bookingPlatform: "Walk-in",
    bookingUrl: "https://ntuchealth.sg/active-ageing/locations",
    programmes: [],
    intensityRange: ["low", "moderate"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["age_60_plus", "sg_citizen_or_pr"],
    healthierSgLinked: true,
    sdohAlignment: ["social_isolation", "financial_strain"],
    tags: ["seniors", "social", "befriending", "exercise", "screening", "free", "walk-in"],
    operatingHours: "Mon-Fri: 8.30am-6pm. Closed weekends & PH.",
    latitude: 1.2870,
    longitude: 103.8084,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-lengkok-bahru",
    notes: "Near rental blocks — SDOH-sensitive population. Walking distance from Lengkok Bahru HDB.",
  },

  {
    resourceId: "AAC-E01",
    name: "NTUC Health Active Ageing Centre (Care) (Heartbeat@Bedok)",
    type: "aac_care",
    region: "east",
    planningAreas: ["Bedok", "Kampong Chai Chee"],
    postalCode: "469662",
    postalSectorPrefix: "46",
    address: "11 Bedok North Street 1, #01-11, Singapore 469662",
    operator: "NTUC Health",
    contactPhone: "",
    contactEmail: "activeageing@ntuchealth.sg",
    bookingPlatform: "Walk-in",
    bookingUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-care-heartbeat-bedok",
    programmes: [],
    intensityRange: ["low", "moderate"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["age_60_plus", "sg_citizen_or_pr"],
    healthierSgLinked: true,
    sdohAlignment: ["social_isolation", "financial_strain"],
    tags: ["seniors", "social", "befriending", "exercise", "screening", "daycare", "rehab", "free", "walk-in"],
    operatingHours: "Mon-Fri: 8.30am-6pm. Closed weekends & PH.",
    latitude: 1.3265,
    longitude: 103.9318,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-care-heartbeat-bedok",
    notes: "Co-located with Active Health Lab, polyclinic, CC. Includes day care and community rehab.",
  },

  {
    resourceId: "AAC-E02",
    name: "NTUC Health Active Ageing Centre (Kampung Kembangan)",
    type: "aac",
    region: "east",
    planningAreas: ["Eunos", "Kembangan", "Kampong Ubi"],
    postalCode: "410102",
    postalSectorPrefix: "41",
    address: "Blk 102 Lengkong Tiga, #01-389, Singapore 410102",
    operator: "NTUC Health",
    contactPhone: "",
    contactEmail: "activeageing@ntuchealth.sg",
    bookingPlatform: "Walk-in",
    bookingUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-kampung-kembangan",
    programmes: [],
    intensityRange: ["low", "moderate"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["age_60_plus", "sg_citizen_or_pr"],
    healthierSgLinked: true,
    sdohAlignment: ["social_isolation"],
    tags: ["seniors", "social", "befriending", "exercise", "screening", "free", "walk-in"],
    operatingHours: "Mon-Fri: 8.30am-6pm. Closed weekends & PH.",
    latitude: 1.3210,
    longitude: 103.9070,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-kampung-kembangan",
    notes: "Serves Eunos, Kembangan, Kampong Ubi seniors.",
  },

  {
    resourceId: "AAC-NE01",
    name: "NTUC Health Active Ageing Centre (Serangoon Central)",
    type: "aac",
    region: "north_east",
    planningAreas: ["Serangoon Central", "Upper Serangoon"],
    postalCode: "550424",
    postalSectorPrefix: "55",
    address: "Blk 424 Serangoon Central, #01-324, Singapore 550424",
    operator: "NTUC Health",
    contactPhone: "",
    contactEmail: "activeageing@ntuchealth.sg",
    bookingPlatform: "Walk-in",
    bookingUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-serangoon-central",
    programmes: [],
    intensityRange: ["low", "moderate"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["age_60_plus", "sg_citizen_or_pr"],
    healthierSgLinked: true,
    sdohAlignment: ["social_isolation"],
    tags: ["seniors", "social", "befriending", "exercise", "screening", "free", "walk-in"],
    operatingHours: "Mon-Fri: 8.30am-6pm. Closed weekends & PH.",
    latitude: 1.3505,
    longitude: 103.8735,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-serangoon-central",
    notes: "Anchor AAC for North-East region.",
  },

  {
    resourceId: "AAC-W01",
    name: "NTUC Health Active Ageing Centre (Nanyang)",
    type: "aac",
    region: "west",
    planningAreas: ["Jurong West", "Boon Lay"],
    postalCode: "640817",
    postalSectorPrefix: "64",
    address: "Blk 817 Jurong West Street 8, Singapore 640817",
    operator: "NTUC Health",
    contactPhone: "",
    contactEmail: "activeageing@ntuchealth.sg",
    bookingPlatform: "Walk-in",
    bookingUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-nanyang",
    programmes: [],
    intensityRange: ["low", "moderate"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["age_60_plus", "sg_citizen_or_pr"],
    healthierSgLinked: true,
    sdohAlignment: ["social_isolation", "financial_strain"],
    tags: ["seniors", "social", "befriending", "exercise", "screening", "free", "walk-in"],
    operatingHours: "Mon-Fri: 8.30am-6pm. Closed weekends & PH.",
    latitude: 1.3400,
    longitude: 103.6980,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-nanyang",
    notes: "Anchor AAC for West region — Jurong West, Boon Lay.",
  },

  {
    resourceId: "AAC-W02",
    name: "NTUC Health Active Ageing Centre (Care) (Bukit Batok West)",
    type: "aac_care",
    region: "west",
    planningAreas: ["Bukit Batok", "Hillview"],
    postalCode: "650439",
    postalSectorPrefix: "65",
    address: "Blk 439 Bukit Batok West Ave 8, #02-01, Singapore 650439",
    operator: "NTUC Health",
    contactPhone: "",
    contactEmail: "activeageing@ntuchealth.sg",
    bookingPlatform: "Walk-in",
    bookingUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-care-bukit-batok-west",
    programmes: [],
    intensityRange: ["low", "moderate"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["age_60_plus", "sg_citizen_or_pr"],
    healthierSgLinked: true,
    sdohAlignment: ["social_isolation"],
    tags: ["seniors", "social", "befriending", "exercise", "screening", "daycare", "rehab", "free", "walk-in"],
    operatingHours: "Mon-Fri: 8.30am-6pm. Closed weekends & PH.",
    latitude: 1.3480,
    longitude: 103.7470,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-care-bukit-batok-west",
    notes: "AAC (Care) — includes day care and community rehabilitation.",
  },

  {
    resourceId: "AAC-W03",
    name: "NTUC Health Active Ageing Centre (Bukit Panjang)",
    type: "aac",
    region: "west",
    planningAreas: ["Bukit Panjang", "Senja", "Fajar"],
    postalCode: "679947",
    postalSectorPrefix: "67",
    address: "2 Bukit Panjang Ring Road, #02-06, Singapore 679947",
    operator: "NTUC Health",
    contactPhone: "",
    contactEmail: "activeageing@ntuchealth.sg",
    bookingPlatform: "Walk-in",
    bookingUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-bukit-panjang",
    programmes: [],
    intensityRange: ["low", "moderate"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["age_60_plus", "sg_citizen_or_pr"],
    healthierSgLinked: true,
    sdohAlignment: ["social_isolation"],
    tags: ["seniors", "social", "befriending", "exercise", "screening", "free", "walk-in"],
    operatingHours: "Mon-Fri: 8.30am-6pm. Closed weekends & PH.",
    latitude: 1.3810,
    longitude: 103.7640,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-bukit-panjang",
    notes: "Serves Bukit Panjang, Senja, Fajar estates.",
  },

  {
    resourceId: "AAC-N01",
    name: "NTUC Health Active Ageing Centre (Care) (Kampung Admiralty)",
    type: "aac_care",
    region: "north",
    planningAreas: ["Admiralty", "Woodlands"],
    postalCode: "730676",
    postalSectorPrefix: "73",
    address: "676 Woodlands Drive 71, #06-01, Singapore 730676",
    operator: "NTUC Health",
    contactPhone: "",
    contactEmail: "activeageing@ntuchealth.sg",
    bookingPlatform: "Walk-in",
    bookingUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-care-kampung-admiralty",
    programmes: [],
    intensityRange: ["low", "moderate"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["age_60_plus", "sg_citizen_or_pr"],
    healthierSgLinked: true,
    sdohAlignment: ["social_isolation", "financial_strain"],
    tags: ["seniors", "social", "befriending", "exercise", "screening", "daycare", "rehab", "free", "walk-in"],
    operatingHours: "Mon-Fri: 8.30am-6pm. Closed weekends & PH.",
    latitude: 1.4398,
    longitude: 103.8000,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://ntuchealth.sg/active-ageing/locations/active-ageing-centre-care-kampung-admiralty",
    notes: "Kampung Admiralty integrated hub. Includes day care and community rehab.",
  },

  // ==================== HPB NATIONAL PROGRAMMES ====================

  {
    resourceId: "HPB-001",
    name: "Start2Move (6-Session Beginner Programme)",
    type: "hpb_programme",
    region: "national",
    planningAreas: [],
    postalCode: "",
    postalSectorPrefix: "",
    address: "Various locations nationwide",
    operator: "Health Promotion Board (HPB)",
    contactPhone: "1800 223 1313",
    contactEmail: "HPB_Mailbox@hpb.gov.sg",
    bookingPlatform: "Healthy 365 app",
    bookingUrl: "https://www.healthhub.sg",
    programmes: [
      { name: "Session 1 — Introduction and Taster Workout", intensity: "low", sessions: 1, priceSgd: 0 },
      { name: "Session 2 — Upper Body Strength, Balance & Flexibility", intensity: "moderate", sessions: 1, priceSgd: 0 },
      { name: "Session 3 — Lower Body Strength, Balance & Flexibility", intensity: "moderate", sessions: 1, priceSgd: 0 },
      { name: "Session 4 — Aerobic Fitness 101s", intensity: "moderate", sessions: 1, priceSgd: 0 },
      { name: "Session 5 — Build Your Own Workout", intensity: "moderate", sessions: 1, priceSgd: 0 },
      { name: "Session 6 — Graduation and Full Body Workout", intensity: "moderate", sessions: 1, priceSgd: 0 },
    ],
    intensityRange: ["low", "moderate"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["all_adults", "age_18_plus"],
    healthierSgLinked: true,
    sdohAlignment: ["financial_strain"],
    tags: ["exercise", "beginner", "free", "group", "national", "pavs_below_150"],
    operatingHours: "Check Healthy 365 app for nearest session schedule",
    latitude: null,
    longitude: null,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.healthhub.sg",
    notes: "Primary CTA for PAVS <150 min/wk. Free. Register via Healthy 365 app > Explore > Events > Start2Move.",
  },

  {
    resourceId: "HPB-002",
    name: "Move It — Adults 19-49 Workout Library",
    type: "hpb_programme",
    region: "national",
    planningAreas: [],
    postalCode: "",
    postalSectorPrefix: "",
    address: "Online — HealthHub",
    operator: "Health Promotion Board (HPB)",
    contactPhone: "1800 223 1313",
    contactEmail: "HPB_Mailbox@hpb.gov.sg",
    bookingPlatform: "HealthHub website",
    bookingUrl: "https://www.healthhub.sg",
    programmes: [],
    intensityRange: ["low", "moderate", "vigorous"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["adults_19_49"],
    healthierSgLinked: true,
    sdohAlignment: ["financial_strain"],
    tags: ["exercise", "self-directed", "video", "free", "national", "home-based", "hiit", "bodyweight", "core"],
    operatingHours: "24/7 online access",
    latitude: null,
    longitude: null,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.healthhub.sg",
    notes: "Includes Beginner Bodyweight, HIIT #1-12, Cardio Blast, Cardio HIIT, SPAR, Core, Pilates, Megadanz.",
  },

  {
    resourceId: "HPB-003",
    name: "Move It — Seniors 50+ Workout Library",
    type: "hpb_programme",
    region: "national",
    planningAreas: [],
    postalCode: "",
    postalSectorPrefix: "",
    address: "Online — HealthHub",
    operator: "Health Promotion Board (HPB)",
    contactPhone: "1800 223 1313",
    contactEmail: "HPB_Mailbox@hpb.gov.sg",
    bookingPlatform: "HealthHub website",
    bookingUrl: "https://www.healthhub.sg",
    programmes: [],
    intensityRange: ["low", "moderate"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["age_50_plus"],
    healthierSgLinked: true,
    sdohAlignment: ["financial_strain", "social_isolation"],
    tags: ["exercise", "self-directed", "video", "free", "national", "home-based", "seniors", "chair", "mobility", "balance"],
    operatingHours: "24/7 online access",
    latitude: null,
    longitude: null,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.healthhub.sg",
    notes: "Includes Full Mobility, Limited Mobility, Chair Pilates, Retro Dance, 7 Easy Exercises (Seated), Strength/Balance/Flexibility series.",
  },

  {
    resourceId: "HPB-004",
    name: "Healthy 365 Step & Eat Challenge",
    type: "hpb_programme",
    region: "national",
    planningAreas: [],
    postalCode: "",
    postalSectorPrefix: "",
    address: "Mobile app — Healthy 365",
    operator: "Health Promotion Board (HPB)",
    contactPhone: "1800 223 1313",
    contactEmail: "HPB_Mailbox@hpb.gov.sg",
    bookingPlatform: "Healthy 365 app",
    bookingUrl: "https://www.healthhub.sg",
    programmes: [],
    intensityRange: ["low"],
    priceRangeSgd: { min: 0, max: 0 },
    eligibility: ["all_adults"],
    healthierSgLinked: true,
    sdohAlignment: [],
    tags: ["activity", "gamified", "rewards", "national", "free", "nutrition", "steps"],
    operatingHours: "24/7",
    latitude: null,
    longitude: null,
    active: true,
    lastVerified: now,
    verifiedBy: "5xiigOWnezOAuF4noNx6wWtr9sn1",
    sourceUrl: "https://www.healthhub.sg",
    notes: "Gamified step tracking and healthier meal rewards. Supplementary CTA for all PAVS tiers.",
  },
];

// ============================================================
// BATCH UPLOAD FUNCTION
// ============================================================

async function seed() {
  const batch = db.batch();
  let count = 0;

  for (const resource of resources) {
    const docRef = db.collection("resources").doc(resource.resourceId);
    batch.set(docRef, resource);
    count++;
  }

  await batch.commit();
  console.log(`\n✅ Successfully seeded ${count} resources into Firestore 'resources' collection.`);
  console.log("\nResource breakdown:");
  
  const types = {};
  resources.forEach(r => { types[r.type] = (types[r.type] || 0) + 1; });
  Object.entries(types).forEach(([type, n]) => console.log(`   ${type}: ${n}`));

  const regions = {};
  resources.forEach(r => { regions[r.region] = (regions[r.region] || 0) + 1; });
  console.log("\nBy region:");
  Object.entries(regions).forEach(([region, n]) => console.log(`   ${region}: ${n}`));

  process.exit(0);
}

seed().catch(err => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
